version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Africa/Lagos
    open-pull-requests-limit: 10
    reviewers:
      - lawaladekunle
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Africa/Lagos
    open-pull-requests-limit: 10
    reviewers:
      - lawaladekunle
    labels:
      - dependencies
      - backend
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: monthly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: monthly
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - ci
